= Projets : Instructions UML

Voir aussi : https://github.com/oliviercailloux/UML/blob/master/Projets%20-%20D%C3%A9marrage.adoc[Démarrage] ; https://github.com/oliviercailloux/java-course/blob/master/L3/Projets.adoc[Instructions générales].
Ce document contient les instructions spécifiques au cours UML.

Une itération UML se conclut par une livraison, qui a pour objectif de documenter le projet ou le futur du projet. Elle ne touche, sauf exception, qu’au contenu du sous-répertoire `Doc`. (DOC)

Vos contributions devraient concerner les deux éléments suivants.

* Le modèle UML Papyrus. Il est une partie importante de vos rendus et doit être soigné. Bien qu’invisible pour les lecteurs, un modèle clair et bien entretenu facilite grandement l’entretien de la documentation, et constitue une clarification conceptuelle en soi pour ceux qui y accèdent.
* La documentation visible. Elle doit être au format Asciidoctor (sauf exception approuvée), appuyée sur des diagrammes typiquement issus de votre modèle UML, ou d’autres documents. Exemples : rapport concernant l’état actuel du projet sur un aspect donné, diagramme de classe montrant l’issue envisagée de la première itération, dessin d’une interface graphique envisagée, comparaison avant / après un changement planifié…

Votre plan de démarrage d’itération doit faire référence à ces documents.

Attention, votre lecteur n’est pas intéressé par l’historique de votre projet. Il faut construire un seul document cohérent, comportant uniquement les informations intéressant votre lecteur : l’état actuel ou futur du projet, pas son état passé (sauf exceptions). Votre documentation ne doit donc pas indiquer, par exemple, ce que vous avez ajouté spécifiquement cette année. Remplacez les parties adéquates de documentation existante par vos propositions, et ajoutez ce qui convient aux endroits adéquats. (Vous pouvez cependant occasionnellement et temporairement indiquer un lien vers une ancienne version d’un diagramme en attendant de coder vos changements proposés, par exemple.) (MAINTAIN)

== Instructions de modélisation
Votre objectif principal est la clarté conceptuelle. 

* Ne collez pas à la structure Java si ce n’est pas justifié. Par exemple : indiquez en UML une propriété publique plutôt qu’une propriété privée assortie d’un getter et d’un setter ; utilisez les paramètres par défaut bien qu’ils ne soient pas implémentés tels quels en Java ; utilisez les multiplicités UML plutôt que les types `List` ou autres collections.
* Supprimez les compartiments vides dans les diagrammes de classe et autres éléments visuels non informatifs; ne représentez pas de façon redondante les mêmes propriétés dans une association et comme un attribut. (ESSENTIAL)

Veuillez exporter vos diagrammes issus du modèle UML en SVG et les présenter, ne fût-ce que succinctement, dans des documents Asciidoctor. Votre documentation doit être lisible via un navigateur web, pas uniquement depuis Papyrus. (SVG)

== Instructions de remise
Résumez dans la description de la PR créée ce que vous proposez, en un paragraphe (référez à un document soumis si utile). Si vous modifiez des diagrammes, ajoutez dans la description de la PR des liens vers les versions précédentes (utilisez l’historique accessible sur GitHub), pour que je puisse mesurer votre travail.

De manière générale : vos documents soumis doivent comporter la documentation du projet utile aux contributeurs du projet ; la description de la PR doit comporter les informations qui ne sont utiles que pour mon évaluation de votre travail.

