= Projets : démarrage

== Affectation initiale
* https://github.com/oliviercailloux/projets/tree/master/Énoncés[Énoncés]
* Max. une équipe par sujet
* Équipes de 4 à 7
* Obligation d’accepter membres supplémentaires à la demande si < 7
* Inscription dans colonne : noter tous les noms. Il faut être au moins 4 pour noter son nom. S’effacer d’une colonne si on s’inscrit dans une autre.
* Si conflit : plus grosse équipe prioritaire ; puis première équipe inscrite (lexicographiquement)

Les énoncés contiennent _beaucoup_ plus de propositions que ce que vous serez capables d’implémenter cette année. Placez l’emphase sur ce qui vous intéresse.

== Démarrage
* Acceptez https://classroom.github.com/g/kQjleEgF[cette mission], avec le nom d’équipe précisément égal au nom du dépôt existant (le nom technique du projet). Cela crée un nouveau « remote » pour votre projet.
* Clonez le projet dont vous partez sur votre machine pour créer un dépôt local contenant l’historique actuel du projet.
* Utilisez la commande `git remote` pour effacer le « remote » `origin` sur votre dépôt local.
* Suivez les instructions de GitHub pour ajouter le nouveau « remote » que vous venez de créer pour votre projet.

Prenez le temps de réfléchir ensemble globalement au projet et tracez les grandes lignes de votre ambition à la fin de l’année. Inutile d’élaborer un plan détaillé, car il serait impossible à respecter, mais cette étape de réflexion dans les grandes lignes est utile pour vous donner un sens commun de votre objectif global.

Placez l’emphase en fonction de vos intérêts (plutôt GUI, plutôt manipulation de fichiers, plutôt web, …).

