= Trucks
An exercice about UML and object-oriented design.

== One driver, one truck
We are building an API to manage trucks and their drivers. We have defined a `Person`: someone that may be driving a truck (or may be idle). We also have a concept of a `Truck`: something that we can start and stop, and that has a designated (or “usual”) driver. 

A driver of a truck is in the truck if and only if her truck is started.

Consider the diagrams below. They show the public behavior of trucks and drivers, that is, what we expect our API user to be able to do with it and how it should react. In particular, the sequence diagram shows that a driver is initially considered idle, but after having started a truck, its driver should then be considered in the truck.

Your mission is to complete the diagrams so as to show one possible implementation of this API (there are several correct answers). In particular, you will need to indicate which attributes the classes have; and complete the sequence diagram to show how the `usualDriver` gets created, and what happens that permits the driver to answer differently to the second call of `isInTruck()`, compared to the first call.

You can clone this repository and import this folder’s Papyrus files, to work on the basis of the existing model.

[[Class]]
.A class diagram showing the publicly accessible operations on our main classes.
image::Public%20view.svg[opts="inline"]

[[Sequence]]
.A sequence diagram showing the desired behavior of our publicly accessible operations.
image::Driver%20overview.svg[opts="inline"]

.Elements of correction
[%collapsible]
====
. A truck must have a `usualDriver`: `Truck` must be associated to `Person` and the association must be navigable from `Truck` to `Person` (a Composition would be adequate here)
. The sequence diagram must show that `truck` creates a `usualDriver` when `truck` is created
. A `Person` must have a boolean attribute `isInTruck`
. This attribute must be `false` by default
. `truck` must send a message to `usualDriver` to change its state when the truck starts: `Person` must have an operation `startDriving` (it is implied, or can be documented by text, that this will change the value of its attribute `isInTruck`)

This is only one possible correction. Others are possible. For example, the association could be navigable from the person to its truck, which permits to get rid of the `isInTruck` attribute, by adding an `isStarted()` operation on the truck.
====

== Shared drivers
We now wish to make it possible for several trucks to share a driver. A driver can still be in at most one truck at a time, of course. To ensure this, we decide that starting one truck automatically stops all the trucks that have the same driver.

Change your model in order to produce a class diagram showing how this design can be achieved. Produce a sequence diagram, featuring two trucks sharing one driver, in order to show what happens (in details) when one truck is started, then the other truck is started. Add an operation `isStarted()` to your `Truck` in order to show their behaviors clearly.

