= Starting up a Papyrus model

== Prerequisites
You know how to manipulate Eclipse views. You have https://github.com/oliviercailloux/UML/blob/master/Papyrus/Various.adoc#Install[installed] Papyrus.

== A new Papyrus model

* You can put your Papyrus model in any kind of project. (You can also create a `Papyrus project`, but I didn’t find any advantage of doing so.)
** If you do not have a project available to hold your model, create an empty “General” project: `File` / `New` / `Project…` / `General` / `Project`
* In that project, create an empty model: `File` / `New` / `Other…` / `Papyrus` / `Papyrus Model`.
** Keep selected as `Architecture Contexts`: `Software Engineering` / `UML`, and as `Architecture Viewpoints` keep both `Software Analysis` and `Software Design` (to have all kinds of diagrams available)
** Name it `My model.di`, for example
** Keep every representations unchecked; uncheck “A UML model with basic primitive types” to start as clean as possible; load no template or profile.
* You model is created. It consists of three files, that you see in the Project explorer view. Open these files with a text editor to check their content.
** `My model.di` contains a simple `ArchitectureDescription` XML element which identifies the project to Papyrus. This file will typically not change when modifying the model or diagrams
** `My model.notation` currently contains a simple XML element but it will evolve when you will add graphical content to your model
** `My model.uml` starts with a simple XML `uml:Model` element (`uml` references the namespace `\http://www.eclipse.org/uml2/5.0.0/UML`), but will evolve to record every UML elements you put in your model, excluding the graphical content.
* Open up the `Model Explorer` view in Eclipse. You see your root model element.
** You can right-click elements in that view to add elements and diagrams to your model. Let us try to add and remove an element. Right-click your root element and, from the `New Child` menu, add a `Comment` element.
** Your `Model Explorer` displays more details that you need. Click `Toggle advanced ModelExplorer` (if it was enabled) to make it display only your root element and the child element you just created.
** Select this new element and hit the delete key to remove it. (You can also use `Undo`.)
** The `Model Explorer` view displays your components as a hierarchy, which reflects the _ownership_ hierarchy of UML elements: an element displayed as “contained” in another element in that view has that other element as its UML owner.
* Open up the `Properties` view. Make sure that both the `Model Explorer` and the `Properties` view are visible on your screen at the same time.
* Select your root model element. In general, the properties view permit to edit all kinds of properties of your model elements. All the properties you will need to edit in this course are in the `UML` tab in the properties view, thus, you can neglect the other tabs such as `Profile` or `Advanced`. You may edit the name of your root model element if you wish (you can also rename your element directly from the `Model Explorer` view). When we will create other model elements, this view will be important.

Note for the curious users: if you wonder where the properties you specified when creating the model (for example, the architecture contexts) are stored, see https://github.com/oliviercailloux/UML/blob/master/Papyrus/Various.adoc#storage-of-properties[this remark]. 


