= Sequences
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182.
:emptyattribute:

== Prerequisites
You https://github.com/oliviercailloux/UML/blob/master/Papyrus/Create.adoc[created] a Papyrus model and followed the https://github.com/oliviercailloux/UML/blob/master/Papyrus/Classes/Classes.adoc[Classes] tutorial.

== Sequences
You should already have in your model a class `Person` with a `fullName` and an ability to `sayHello()`, and a specialization of it, `User`, who has a `contact` person.
We will now create two lifelines that represent a user sending a message `sayHello()` to its contact person, and display them in a Sequence diagram.

* Add an `Interaction` element as a sub-element of your root element, name it `User to contact`.
* Add a `Property` element as a sub-element of `User to contact`, name it `user` and give it a type of `User`.
** Remember to use auto-completion for choosing the type, as we have learned in the Classes document.
* Add a `Lifeline` element named `User lifeline` as another sub-element of `User to contact`
** In the properties of `User lifeline`, indicates that it represents your property `user`.
* Add another `Lifeline` element named `Contact lifeline`; indicate that it represents the property `contact` of the class `User`.

Let’s now display these two lifelines in a diagram and add a message from `user` to its `contact`.

* Add a Sequence diagram as a child of your `User to contact` element, name it `User says hello to its contact person`.
* Drag the `User lifeline` element to the left part of the diagram.
* Drag the `Contact lifeline` element to the right of it.
* In the `Edges` Palette (to the right of the Papyrus diagram editor), click `Message Sync`, then click the `user` lifeline representation, then click the `contact` lifeline representation.
** You see an arrow appear from one lifeline to its neighbor lifeline, representing the message being sent.
** Name it `User says hello message`.
** In the properties of the `User says hello message`; as its signature, choose the operation `sayHello()` (defined on `Person`).
** Observe that the label displayed on this message representation in the sequence diagram changes to indicate the signature instead of its name. This is what we want.
** Observe that Papyrus has created several elements for you in supplement to the message send: a `BehaviorExecutionSpecification` representing the execution required to treat the message; a return message that is sent when the object has finished treating the message; and four event occurrences, produced when the messages are sent and received. Give to the `BehaviorExecutionSpecification` element the name `sayHello execution`.
** Finally, hide the label on the representation of the message returning from the contact lifeline back to the user lifeline, with `Filters` / `Hide All Labels`.

Remember that the messages sent to a property of type `T` are valid only if the type `T` indeed defines an operation corresponding to the signature of the message. In our case, we can send the message having signature `sayHello()` to `contact` because `Person` indeed defines an operation `sayHello()`. (Unfortunately, it seems that the current version of Papyrus does not complain when this constraint is broken.)

As a second exercice, let’s represent an execution that requires several sub-executions. Assume that the contact persons requires three steps to say hello: first, think, second, open mouth, third, utter the message.

* Let’s start by relating our existing execution to a behavior, for clarity.
** Add, as a child of `Person`, an `OpaqueBehavior` as `ownedBehavior`. Name it `sayHello behavior`. A behavior represents an implementation of a `FeaturedClassifier` (in this case, of the `Operation` element `sayHello()`).
** In the properties of `sayHello behavior`, indicate that its Specification is the `sayHello()` operation.
** Select the `sayHello()` element and observe that it now has `sayHello behavior` listed in the `Method` box.
** Select the element `sayHello execution`. In its properties, indicate that its Behavior is `sayHello behavior`. You see this label appear next to the execution representation in the Sequence diagram.
* Now add, as childs of `Person`, three more `OpaqueBehavior` elements as `ownedBehavior`. Name them `think behavior`, `open mouth behavior` and `utter message behavior`.
* Only remains to add three executions to our Sequence diagram representing the execution of these behaviors, in sequence.
** In the `Nodes` Palette of the Papyrus diagram editor, click `Behavior Execution Specification`, then click the representation of `sayHello execution` in the `contact` Lifeline (click just under the `sayHello behavior` label). Observe that Papyrus has added to the model, in supplement to the `BehaviorExecutionSpecification` element, two `ExecutionOccurrenceSpecification` elements, representing the start and end event occurrences of that behavior. Name the `BehaviorExecutionSpecification` element that has just been added `think execution`. In its properties, define as its Behavior the `think behavior` element.
** Proceed similarly for creating a `open mouth execution` and a `utter message execution` elements, representing executions of the corresponding behaviors.

Note that UML permits to also specify messages to start such behaviors. In this case, a message invoking an operation `think` could be represented as going from the `sayHello execution` representation to the `think execution` representation, with the semantics that this message would be the start event occurrence of the `think execution` execution element. But, this is currently quite hard to achieve, because of bugs in the current version of Papyrus.

