= Sequences
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182.
:emptyattribute:

== Prerequisites
You https://github.com/oliviercailloux/UML/blob/master/Papyrus/Create.adoc[created] a Papyrus model and followed the https://github.com/oliviercailloux/UML/blob/master/Papyrus/Classes.adoc[Classes] tutorial.

== Sequences
You should already have in your model a class `Person` with a `fullName` and an ability to `sayHello()`, and a specialization of it, `User`, who has a `contact` person.
We will now create two lifelines that represent a user sending a message `sayHello()` to its contact person, and display them in a Sequence diagram.

* Add an `Interaction` element as a sub-element of your root element, name it `User to contact`.
* Add a `Property` element as a sub-element of `User to contact`, name it `user` and give it a type of `User`.
** Remember to use auto-completion for choosing the type, as we have learned in the Classes document.
* Add a `Lifeline` element named `User lifeline` as another sub-element of your root element
** In the properties of `User lifeline`, indicates that it represents your property `user`.
* Add another `Lifeline` element named `Contact lifeline`; indicate that it represents the property `contact` of the class `User`.
* Add another `Lifeline` relationship to your `User`, select `Person` as target.

Let’s now display these two lifelines in a diagram and add a message from `user` to its `contact`.

* Add a Sequence diagram as a child of your `User to contact` element, name it `User says hello to its contact person`.
* Drag the `User lifeline` element to the left part of the diagram.
* Drag the `Contact lifeline` element to the right of it.
* In the `Edges` Palette (to the right of the Papyrus diagram editor), click `Message Sync`, then click the `user` lifeline representation, then click the `contact` lifeline representation.
** You see an arrow appear from one lifeline to its neighbor lifeline, representing the message being sent.
** Name it `User says hello message`.
** In the properties of the `User says hello message`, choose the operation `sayHello()` (defined on `Person`) as its signature.
** Observe that the label displayed on this message representation in the sequence diagram changes to indicate the signature instead of its name. This is what we want.
** Observe that Papyrus has created several elements for you in supplement to the message send: a `BehaviorExecutionSpecification` representing the behavior of the class treating the message; a return message that happens when the object has finished treating the message; and four events, produced when the messages are sent and received.
** Finally, hide the label on the representation of the message returning from the contact lifeline back to the user lifeline, with `Filters` / `Hide All Labels`.

