= Use cases

== Prerequisites
You https://github.com/oliviercailloux/UML/blob/master/Papyrus/Create.adoc[created] a Papyrus model.

== Use cases
Let’s add a use case and related elements to our model, then display them in a diagram. Suppose we want to indicate that our system is able to say hello when demanded by a user.

* Add an `Interaction` element as a sub-element of your root element, name it `System`.
** A good use case has a subject. A subject can be any kind of `Classifier`. We choose to create an `Interaction` element for this purpose (other kinds would work as well). In our example, the use cases describe the system itself, hence its name.
* Add a `Use case` element as a sub-element of your `System` element. Name it `Say hello`.
* In the properties of the `Say hello` element, find the Subject area, click the Plus icon to add a subject, select the `System` element and let it move to the right part of the screen. Check that it now appears in the box for the subjects of `Say hello`.
** Look at the properties of the `System` element: you see that `Say hello` has been added as one of its Use case.
* Add an `Actor` element as a sub-element of your root element, name it `User`.
//* Add an `Association` element as a sub-element of your root element, name it `User triggers say hello`.

Now for the diagram.

* Add a Use Case diagram as a child of your root element, name it `User demands to say hello`.
* Drag the `System` element in the middle of the diagram.
* Drag the `Say hello` element into the `System` representation, choose either `Use case` or `Drop` (I could find no difference). (Selecting a “default strategy” does not persist after Eclipse restart.)
* Drag the `User` element in the left part of the diagram.
* In the Palette (in the diagram), in the Links part, click Association, and create an association from `User` to `Say hello` (by clicking on the corresponding representations). Name it `User triggers say hello`. 
** The Association element appears in the model.
** It owns two properties, corresponding to the its ends: one that has the `User` as type, and one that has the `Say hello` as type.
* Right-click the line representing the association, `Filters` / `Show/Hide Labels`, unselect its name.
* Remove the association representation https://github.com/oliviercailloux/UML/blob/master/Papyrus/Various.adoc#Representation[from the diagram] and drag it again in the diagram.
* Click the name of the association in the diagram and select `Delete from diagram`

In you are curious about the `Filters` / `Synchronized with Model` option, read https://github.com/oliviercailloux/UML/blob/master/Papyrus/Various.adoc#Synchronization[this].

