= Various remarks about Papyrus

[[Install]]
== Installing Papyrus
I recommend installing Papyrus over your Eclipse installation.

* On the Papyrus https://www.eclipse.org/papyrus/download.html[download page], you will find the update site URL. Clicking on it reveals instructions that should be followed. You can then install the “Papyrus for UML” feature (you do not need the other ones).
* Then, using the update site http://download.eclipse.org/modeling/mdt/papyrus/components/designer/, install Papyrus Java profile, library and code generation (Incubation) 1.1.0. (This adds a Utils sub-menu for dealing with properties, and some reverse generation capabilities that we will not need.)

== Storage of properties
Papyrus unfortunately stores some of the properties of your model not in the file hierarchy of the project itself, but in your Eclipse workspace (specifically, in `.metadata/.plugins/org.eclipse.papyrus.infra…`). Thus, if you transfer the project to someone else, these properties will not be transferred, and are not versioned easily in a CVS. This concerns generally those properties that belong to Papyrus and not to UML, including: the enabled `Architecture Viewpoints`, the choice of using internationalization, or the profiles to load (the imports, however, are part of your UML model and are stored in the `.uml` file). Fortunately, these files do not matter much as they do not change the semantics of your model.

[[Representation]]
== Element VS representation of elements
An important aspect of a real UML modeling software (compared to a software designed to draw graphics without having a model as a basis, such as https://draw.io/) is that what is shown in a diagram represent model elements, and these elements exist independently of their representation in a diagram. Thus, it is important to distinguish deleting a _representation_ of an element from a diagram and deleting _the element_ itself. Right-click on a representation in a diagram, and you will see both possibilities in the menu. Try deleting a representation from a diagram, and observe that you can simply drag again the element from the model to the diagram to re-create it if desired.

[[Import]]
== Import, do not merely load
When importing packages, you can choose to (just) load them or to import them. The difference is as follows. If you import a package, it also loads (even if you unload the package, as long as it is imported in your model, it will reload automatically). An imported package is recorded as a part of your UML model. A package that is loaded but not imported is not: the load instruction is only recorded in your Eclipse workspace, so this will not be easily shared with other users of your model. Also, auto-completion for types does not work if you merely loaded a package, it needs to be imported. 

[[Synchronization]]
== Do not synchronize (too much)
Papyrus diagrams let you work in “synchronized” mode. Right-click on any representation in a diagram, select `Filters` / `Synchronized with Model` to activate it for a given representation. 

The term is misleading, though. All representations in all diagrams are necessarily “synchronized” with your model, even when the option is not selected, in the sense that they are representations of the model. Thus, for example, renaming an element in the model will also rename all its representations.

The option in the menu only serves to let Papyrus decide automatically which other elements, related to the one you decide to mark as “Synchonized with Model”, should be shown in the diagram. When the option is checked, you cannot access the “Delete from diagram” option any more on the related representations. However, you can still select which related links should appear (for example), through the `Filters` / `Show/Hide Related Links` menu item.

It is important to realize that a diagram _itself_ can also be “Synchronized with Model”: make sure nothing is selected, then right-click a diagram to enable or disable this global synchronization option. If this is selected, Papyrus will decide automatically the elements showing up on the diagram. For example, on a Class diagram, it will simply show all classes.

I suggest to not select this option (neither the global nor the local synchronization): I find it usually does not help and it is confusing to not be able afterwards to remove some representations manually. You typically want to decide manually which elements you want to show on a diagram. Alternatively, when there are a lot of elements to represent, select the option to let every related elements appear, then immediately de-select it, to save time without suffering limitations.

== Key bindings
Have a look at the key bindings, available using a link in the Papyrus https://wiki.eclipse.org/Papyrus_User_Guide[User Guide].

== Evolution of Papyrus
I find that Papyrus is a very active and promising software, which is the reason I use it for teaching. 

I initially had a converse impression, because its https://www.eclipse.org/forums/index.php/f/121/[forum] is not always very responsive and because it has about https://bugs.eclipse.org/bugs/buglist.cgi?product=Papyrus&limit=0&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED[2500] open bugs (for comparison, GitHub Classroom has about https://github.com/education/classroom/issues[200] open bugs; Eclipse JDT has about https://bugs.eclipse.org/bugs/buglist.cgi?product=JDT&limit=0&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED[5500]). 

In fact, although an important number of bugs opens each year (https://bugs.eclipse.org/bugs/buglist.cgi?product=Papyrus&limit=0&chfield=%5BBug%20creation%5D&chfieldfrom=2019-01-01&chfieldto=2019-12-31[458] in 2019, 600 in 2018, 1386 in 2017, 1717 in 2016, 2094 in 2015, 1239 in 2014, 1044 in 2013, 852 in 2012, 1037 in 2011, 1110 in 2010, 519 in 2009 and 44 in 2008), an almost equally important number of bugs have been fixed each year: https://bugs.eclipse.org/bugs/buglist.cgi?product=Papyrus&limit=0&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&chfield=resolution&chfieldvalue=FIXED&chfieldfrom=2019-01-01&chfieldto=2019-12-31[305] [https://bugs.eclipse.org/bugs/buglist.cgi?product=Papyrus&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&j_top=OR&f4=OP&j4=AND_G&f5=bug_status&f6=bug_status&f7=bug_status&o5=changedto&o6=changedafter&o7=changedbefore&v5=RESOLVED&v6=2019-01-01&v7=2019-12-31&f8=CP&f9=OP&j9=AND_G&f10=bug_status&f11=bug_status&f12=bug_status&o10=changedto&o11=changedafter&o12=changedbefore&v10=VERIFIED&v11=2019-01-01&v12=2019-12-31&f13=CP&f14=OP&j14=AND_G&f15=bug_status&f16=bug_status&f17=bug_status&o15=changedto&o16=changedafter&o17=changedbefore&v15=CLOSED&v16=2019-01-01&v17=2019-12-31&f18=CP[368]] in 2019, 535 [799] in 2018, 1230 [1431] in 2017, 1146 [1332] in 2016, 1311 [1475] in 2015… (In the brackets, the bugs triaged for any reasons, such as being invalid; including in both cases the bugs that have later been reopened then triaged again.)
In particular, among the 600 bugs created in 2018, https://bugs.eclipse.org/bugs/buglist.cgi?product=Papyrus&limit=0&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&chfield=%5BBug%20creation%5D&chfieldfrom=2018-01-01&chfieldto=2018-12-31[393] are now triaged; and among the 458 bugs created in 2019, 232 are now triaged. This suggests that developers do consider new bug reports seriously.

